server:
  name: "amusing-x/pluto"
  httpServer:
    addr: :10003
  grpcServer:
    network: tcp
    address: :20003
mysql:
  plutodb:
    db: pluto
    user: klooktest
    password: sees7&chanting
    host: localhost:3306
    port: 3306
    protocol: tcp
    maxLifeTime: 3600
    maxOpenConns: 100
    maxIdleConns: 10
redis:
  redis1:
    addr: 127.0.0.1:6379
    dbNo: 1